# Generated by Django 3.1.13 on 2021-09-28 16:21
import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0003_auto_20210406_0753"),
        ("reader_studies", "0012_auto_20210825_1346"),
    ]

    operations = [
        migrations.CreateModel(
            name="DisplaySet",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="display_sets", to="cases.Image"
                    ),
                ),
                (
                    "reader_study",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="display_sets",
                        to="reader_studies.readerstudy",
                    ),
                ),
            ],
            options={"ordering": ("created",)},
        ),
    ]
