# Generated by Django 3.1.13 on 2021-11-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_editorrequest"),
    ]

    operations = [
        migrations.RemoveField(model_name="company", name="initial_editor",),
    ]
